# Site settings
title: The SNR Laboratory
email: contact@snr-lab.org
author: root
description: > # this means to ignore newlines until "url:"
  We research all possible ways to improve signal-to-noise in all disciplines.
url: "https://www.snr-lab.org/" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/
youtube_username: "@snr-lab"
github_username: snr-laboratory

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: auto
#permalink: /:year/:title:output_ext

# Front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
