# Site settings
title: The SNR Laboratory
email: contact@snr-lab.org
description: > # this means to ignore newlines until "baseurl:"
  The SNR Laboratory.  We research all possible ways to improve signal-to-noise in all disciplines.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://jekyll.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: snr-laboratory

# Build settings
markdown: kramdown
theme: minima
#permalink: /:year/:title:output_ext
